# Generated by Django 3.1 on 2020-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('starting_bid', models.FloatField()),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
