# Generated by Django 3.1 on 2020-08-25 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 25, 16, 43, 19, 644018)),
        ),
    ]
